#!/usr/bin/env node

/*
 * Copyright (C) 2026 Acoustic, L.P. All rights reserved.
 *
 * Runs at `before_prepare` (iOS).
 *
 * Cordova regenerates the Podfile during prepare by parsing the EXISTING
 * Podfile for pod declarations (not plugin.xml, not pods.json). This hook
 * rewrites the Podfile with the correct static pod declaration BEFORE Cordova
 * reads it, so the generated Podfile carries the right variant into `pod install`.
 *
 * It also updates pods.json so the state stays consistent.
 *
 *   useRelease: true  (or missing) → AcousticConnect    (~> 2.0)
 *   useRelease: false               → AcousticConnectDebug (>= 2.1.12)
 */

'use strict';

var fs   = require('fs');
var path = require('path');

var RELEASE_NAME = 'AcousticConnect';
var RELEASE_SPEC = '~> 2.0';
var DEBUG_NAME   = 'AcousticConnectDebug';
var DEBUG_SPEC   = '>= 2.1.12';
var MIN_IOS      = '15.1';

// Resolve Xcode target/project name from the .xcodeproj directory present
// under platforms/ios. Cordova-iOS 7+ always names it 'App', but derive it
// dynamically so the hook works if the project is renamed.
function resolveProjectName(iosDir) {
    try {
        var entries = fs.readdirSync(iosDir);
        for (var i = 0; i < entries.length; i++) {
            if (entries[i].slice(-10) === '.xcodeproj') {
                return entries[i].slice(0, -10);
            }
        }
    } catch (e) {
        if (e.code !== 'ENOENT') {
            throw new Error('[acoustic-connect] before_prepare: cannot read platforms/ios: ' + e.message);
        }
    }
    return 'App';
}

function buildPodfile(podName, podSpec, deployTarget, projectName) {
    var name = projectName || 'App';
    return (
        '# DO NOT MODIFY -- auto-generated by Apache Cordova\n' +
        "source 'https://cdn.cocoapods.org/'\n" +
        "platform :ios, '" + deployTarget + "'\n" +
        'use_frameworks!\n' +
        "target '" + name + "' do\n" +
        "\tproject '" + name + ".xcodeproj'\n" +
        "\tpod '" + podName + "', '" + podSpec + "'\n" +
        'end\n' +
        '\n' +
        'post_install do |installer|\n' +
        '  installer.generated_projects.each do |project|\n' +
        '    project.targets.each do |target|\n' +
        '      target.build_configurations.each do |config|\n' +
        "        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '" + deployTarget + "'\n" +
        '      end\n' +
        '    end\n' +
        '  end\n' +
        'end\n'
    );
}

module.exports = function (context) {
    var platforms = context.opts.platforms || [];
    if (platforms.length > 0 && platforms.indexOf('ios') === -1) {
        return;
    }

    var projectRoot = context.opts.projectRoot;

    // Read ConnectConfig.json — defaults to release when absent.
    var useRelease = true;
    var configPath = path.join(projectRoot, 'ConnectConfig.json');
    if (fs.existsSync(configPath)) {
        try {
            var cfg = JSON.parse(fs.readFileSync(configPath, 'utf8'));
            if (cfg && cfg.Connect && cfg.Connect.useRelease === false) {
                useRelease = false;
            }
        } catch (e) {
            console.warn('[acoustic-connect] before_prepare: ConnectConfig.json parse error — ' +
                         e.message + '; defaulting to release variant');
        }
    }

    var podName  = useRelease ? RELEASE_NAME : DEBUG_NAME;
    var podSpec  = useRelease ? RELEASE_SPEC : DEBUG_SPEC;

    var iosDir      = path.join(projectRoot, 'platforms', 'ios');
    var projectName = resolveProjectName(iosDir);

    // Rewrite the Podfile with the correct static pod declaration so that
    // Cordova's Podfile parser picks up the right pod when it runs next.
    var podfilePath = path.join(iosDir, 'Podfile');
    if (fs.existsSync(podfilePath)) {
        var newPodfile = buildPodfile(podName, podSpec, MIN_IOS, projectName);
        var existing   = fs.readFileSync(podfilePath, 'utf8');
        if (existing !== newPodfile) {
            fs.writeFileSync(podfilePath, newPodfile, 'utf8');
            console.log('[acoustic-connect] before_prepare: Podfile → ' +
                        podName + ' ' + podSpec);
        }
    }

    // Keep pods.json in sync so the Cordova/Xcode tooling stays consistent.
    var podsJsonPath = path.join(iosDir, 'pods.json');
    if (fs.existsSync(podsJsonPath)) {
        try {
            var pods = JSON.parse(fs.readFileSync(podsJsonPath, 'utf8'));
            var libs = pods.libraries || {};
            var changed = false;

            // Remove whichever variant is wrong.
            var wrongName = useRelease ? DEBUG_NAME : RELEASE_NAME;
            if (libs[wrongName]) {
                delete libs[wrongName];
                changed = true;
            }

            // Ensure the correct variant is present with count ≥ 1.
            if (!libs[podName] || libs[podName].spec !== podSpec) {
                libs[podName] = { name: podName, spec: podSpec, count: 1 };
                changed = true;
            }

            if (changed) {
                pods.libraries = libs;
                fs.writeFileSync(podsJsonPath, JSON.stringify(pods, null, 4), 'utf8');
                console.log('[acoustic-connect] before_prepare: pods.json → ' +
                            podName + ' ' + podSpec);
            }
        } catch (e) {
            throw new Error('[acoustic-connect] before_prepare: failed to update pods.json: ' + e.message);
        }
    }
};
