/*
 * Copyright (C) 2026 Acoustic, L.P. All rights reserved.
 *
 * Fixture-based unit tests for the critical pbxproj / Podfile manipulation
 * helpers in src/ios/hooks/after_prepare.js.
 *
 * pbxproj surgery (target creation, embed wiring, framework linking) is now
 * handled by add_ios_push_extensions.rb (xcodeproj gem) and tested via
 * integration. This file covers the JS helpers that remain in after_prepare.js:
 *   - updatePodfile          (Podfile NSE/NCE target insertion)
 *   - patchXcframeworksScriptPhases  (post-pod-install pbxproj repair)
 *   - resolveConnectConfigPath       (config file resolution)
 *   - resolveIosDevelopmentTeam      (team ID extraction)
 *
 * Functions are exposed via module.exports._internal — not part of the public API.
 */

/* eslint-disable @typescript-eslint/no-var-requires */
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';

// Suppress console noise from the helpers under test.
beforeAll(() => {
    jest.spyOn(console, 'log').mockImplementation(() => {});
    jest.spyOn(console, 'warn').mockImplementation(() => {});
});
afterAll(() => {
    jest.restoreAllMocks();
});

const hook = require('../src/ios/hooks/after_prepare.js');
const {
    updatePodfile,
    patchXcframeworksScriptPhases,
    resolveConnectConfigPath,
    resolveIosDevelopmentTeam,
} = hook._internal as {
    updatePodfile:                 (iosDir: string) => boolean;
    patchXcframeworksScriptPhases: (p: string, variant?: string) => void;
    resolveConnectConfigPath:      (projectRoot: string) => string;
    resolveIosDevelopmentTeam:     (projectRoot: string) => string | null;
};

// ---------------------------------------------------------------------------
// Per-test helpers
// ---------------------------------------------------------------------------

let tmpDir: string;
let pbxprojPath: string;

beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'acoustic-after-prepare-'));
    pbxprojPath = path.join(tmpDir, 'project.pbxproj');
});

afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
});

function writePbxproj(content: string): void {
    fs.writeFileSync(pbxprojPath, content, 'utf8');
}

function readPbxproj(): string {
    return fs.readFileSync(pbxprojPath, 'utf8');
}

// ---------------------------------------------------------------------------
// updatePodfile — NSE / NCE target insertion
//
// Tests the Podfile mutation logic that nests ConnectNSE / ConnectNCE as
// sub-targets of the App target so CocoaPods resolves the host-extension
// relationship correctly.
// ---------------------------------------------------------------------------

describe('updatePodfile — NSE/NCE target insertion', () => {
    function writePodfile(content: string): void {
        fs.writeFileSync(path.join(tmpDir, 'Podfile'), content, 'utf8');
    }

    function readPodfile(): string {
        return fs.readFileSync(path.join(tmpDir, 'Podfile'), 'utf8');
    }

    // Representative Podfile that cordova-ios generates: App target only.
    const BASE_PODFILE = [
        "# DO NOT MODIFY -- auto-generated by Apache Cordova",
        "source 'https://cdn.cocoapods.org/'",
        "install! 'cocoapods', :warn_for_unused_master_specs_repo => false",
        "platform :ios, '15.1'",
        "use_frameworks!",
        "target 'App' do",
        "\tproject 'App.xcodeproj'",
        "\tpod 'AcousticConnectDebug', '>= 2.1.12'",
        "end",
        "",
        "post_install do |installer|",
        "  installer.generated_projects.each do |project|",
        "    project.targets.each do |target|",
        "      target.build_configurations.each do |config|",
        "        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'",
        "      end",
        "    end",
        "  end",
        "end",
        "",
    ].join('\n');

    it("inserts a nested ConnectNSE target inside the App block", () => {
        writePodfile(BASE_PODFILE);
        updatePodfile(tmpDir);
        expect(readPodfile()).toContain("target 'ConnectNSE' do");
    });

    it("inserts a nested ConnectNCE target inside the App block", () => {
        writePodfile(BASE_PODFILE);
        updatePodfile(tmpDir);
        expect(readPodfile()).toContain("target 'ConnectNCE' do");
    });

    it('sets inherit! :search_paths for each extension target', () => {
        writePodfile(BASE_PODFILE);
        updatePodfile(tmpDir);
        const result = readPodfile();
        // Two search_paths declarations — one per extension
        const matches = result.match(/inherit! :search_paths/g) || [];
        expect(matches.length).toBeGreaterThanOrEqual(2);
    });

    it('positions NSE/NCE targets after the App target opener and before the outer end', () => {
        writePodfile(BASE_PODFILE);
        updatePodfile(tmpDir);
        const result = readPodfile();
        const posApp = result.indexOf("target 'App' do");
        const posNSE = result.indexOf("target 'ConnectNSE'");
        const posNCE = result.indexOf("target 'ConnectNCE'");
        expect(posNSE).toBeGreaterThan(posApp);
        expect(posNCE).toBeGreaterThan(posApp);
        expect(posNSE).toBeLessThan(posNCE);
    });

    it('returns true when the Podfile was modified', () => {
        writePodfile(BASE_PODFILE);
        expect(updatePodfile(tmpDir)).toBe(true);
    });

    it('is idempotent — returns false and content unchanged on second run', () => {
        writePodfile(BASE_PODFILE);
        updatePodfile(tmpDir);
        const after1 = readPodfile();
        const changed = updatePodfile(tmpDir);
        expect(changed).toBe(false);
        expect(readPodfile()).toBe(after1);
    });
});

// ---------------------------------------------------------------------------
// patchXcframeworksScriptPhases
// ---------------------------------------------------------------------------

describe('patchXcframeworksScriptPhases', () => {
    // The literal string xcode npm writes for the old single-call form.
    const OLD_SCRIPT =
        '"\\\"${PODS_ROOT}/Target Support Files/AcousticConnectDebug/AcousticConnectDebug-xcframeworks.sh\\\"\\n"';

    const XCFILELIST_SUFFIX =
        'Target Support Files/AcousticConnectDebug/AcousticConnectDebug-xcframeworks-input-files.xcfilelist';
    const CORRECT_INPUT = '"${PODS_ROOT}/' + XCFILELIST_SUFFIX + '"';

    // Minimal pbxproj snippet with a script build phase.
    function makeScriptPhasePbxproj(shellScript: string, inputPath: string): string {
        return [
            '/* Begin PBXShellScriptBuildPhase section */',
            '\t\tAAAAAAAAAAAAAAAAAAAAAAAA /* [CP] Prepare AcousticConnect xcframeworks */ = {',
            '\t\t\tisa = PBXShellScriptBuildPhase;',
            `\t\t\tinputFileListPaths = (\n\t\t\t\t${inputPath},\n\t\t\t);`,
            `\t\t\tshellScript = ${shellScript};`,
            '\t\t};',
            '/* End PBXShellScriptBuildPhase section */',
            '',
        ].join('\n');
    }

    it('replaces the old single-line shellScript invocation with the locking wrapper', () => {
        writePbxproj(makeScriptPhasePbxproj(OLD_SCRIPT, CORRECT_INPUT));
        patchXcframeworksScriptPhases(pbxprojPath, 'AcousticConnectDebug');
        const result = readPbxproj();
        expect(result).not.toContain(OLD_SCRIPT);
        // The wrapper script contains the acoustic locking sentinel
        expect(result).toContain('co.acoustic.xcframeworks.lck');
    });

    it('fixes B1 — unquoted ${PODS_ROOT} xcfilelist path', () => {
        const brokenB1 = '${PODS_ROOT}/' + XCFILELIST_SUFFIX;
        writePbxproj(makeScriptPhasePbxproj(OLD_SCRIPT, brokenB1));
        patchXcframeworksScriptPhases(pbxprojPath, 'AcousticConnectDebug');
        const result = readPbxproj();
        expect(result).toContain(CORRECT_INPUT);
        // Unquoted form must be gone (the comma after it is part of the list entry)
        expect(result).not.toContain(brokenB1 + ',');
    });

    it('fixes B3 — quoted path missing the ${PODS_ROOT} prefix', () => {
        const brokenB3 = '"/' + XCFILELIST_SUFFIX + '"';
        writePbxproj(makeScriptPhasePbxproj(OLD_SCRIPT, brokenB3));
        patchXcframeworksScriptPhases(pbxprojPath, 'AcousticConnectDebug');
        const result = readPbxproj();
        expect(result).toContain(CORRECT_INPUT);
        expect(result).not.toContain(brokenB3);
    });

    it('is idempotent — no change when shellScript and xcfilelist are already correct', () => {
        // A pbxproj that already has the correct input path and a non-old shellScript.
        // patchXcframeworksScriptPhases should not rewrite the file.
        const already = makeScriptPhasePbxproj('"already-patched-wrapper"', CORRECT_INPUT);
        writePbxproj(already);
        patchXcframeworksScriptPhases(pbxprojPath, 'AcousticConnectDebug');
        expect(readPbxproj()).toBe(already);
    });

    it('fixes xcfilelist for release SDK variant (AcousticConnect)', () => {
        const releaseSuffix = 'Target Support Files/AcousticConnect/AcousticConnect-xcframeworks-input-files.xcfilelist';
        const brokenPath    = '${PODS_ROOT}/' + releaseSuffix;
        const correctPath   = '"${PODS_ROOT}/' + releaseSuffix + '"';
        writePbxproj(makeScriptPhasePbxproj('"some-existing-script"', brokenPath));
        patchXcframeworksScriptPhases(pbxprojPath, 'AcousticConnect');
        const result = readPbxproj();
        expect(result).toContain(correctPath);
        expect(result).not.toContain(brokenPath + ',');
    });
});

// ---------------------------------------------------------------------------
// resolveConnectConfigPath
// ---------------------------------------------------------------------------

describe('resolveConnectConfigPath', () => {
    it('returns ConnectConfig.json when it exists', () => {
        const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'cfg-'));
        const p = path.join(dir, 'ConnectConfig.json');
        fs.writeFileSync(p, '{}');
        try {
            expect(resolveConnectConfigPath(dir)).toBe(p);
        } finally {
            fs.rmSync(dir, { recursive: true, force: true });
        }
    });

    it('falls back to ConnectConfig.example.json when ConnectConfig.json is absent', () => {
        const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'cfg-'));
        const p = path.join(dir, 'ConnectConfig.example.json');
        fs.writeFileSync(p, '{}');
        try {
            expect(resolveConnectConfigPath(dir)).toBe(p);
        } finally {
            fs.rmSync(dir, { recursive: true, force: true });
        }
    });

    it('throws when neither file exists', () => {
        const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'cfg-'));
        try {
            expect(() => resolveConnectConfigPath(dir)).toThrow('ConnectConfig.json not found');
        } finally {
            fs.rmSync(dir, { recursive: true, force: true });
        }
    });

    it('prefers ConnectConfig.json over ConnectConfig.example.json when both exist', () => {
        const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'cfg-'));
        const real    = path.join(dir, 'ConnectConfig.json');
        const example = path.join(dir, 'ConnectConfig.example.json');
        fs.writeFileSync(real, '{}');
        fs.writeFileSync(example, '{}');
        try {
            expect(resolveConnectConfigPath(dir)).toBe(real);
        } finally {
            fs.rmSync(dir, { recursive: true, force: true });
        }
    });
});

// ---------------------------------------------------------------------------
// resolveIosDevelopmentTeam
// ---------------------------------------------------------------------------

describe('resolveIosDevelopmentTeam', () => {
    let cfgDir: string;

    beforeEach(() => {
        cfgDir = fs.mkdtempSync(path.join(os.tmpdir(), 'team-'));
    });
    afterEach(() => {
        fs.rmSync(cfgDir, { recursive: true, force: true });
    });

    function writeConfig(obj: object): void {
        fs.writeFileSync(path.join(cfgDir, 'ConnectConfig.json'), JSON.stringify(obj));
    }

    it('returns the team ID from Connect.iOSDevelopmentTeam', () => {
        writeConfig({ Connect: { iOSDevelopmentTeam: 'ABCD1234EF' } });
        expect(resolveIosDevelopmentTeam(cfgDir)).toBe('ABCD1234EF');
    });

    it('returns null when iOSDevelopmentTeam is absent', () => {
        writeConfig({ Connect: { AppKey: 'x' } });
        expect(resolveIosDevelopmentTeam(cfgDir)).toBeNull();
    });

    it('returns null when config file is absent (no throw)', () => {
        expect(resolveIosDevelopmentTeam(cfgDir)).toBeNull();
    });

    it('throws a descriptive error when ConnectConfig.json is malformed JSON', () => {
        fs.writeFileSync(path.join(cfgDir, 'ConnectConfig.json'), '{ not valid json');
        expect(() => resolveIosDevelopmentTeam(cfgDir)).toThrow('malformed JSON');
    });
});
